config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :application_requests
  resources :workplaces
  get 'home/index'
  get 'users', to: "users#index"
	get 'users/new' => "users#new", as: :new_user
	post 'create_user' => "users#create_user", as: :create_user
  root 'workplaces#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/workplace.rb
class Workplace < ApplicationRecord
end

app/controllers/workplaces_controller.rb
class WorkplacesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_workplace, only: [:show, :edit, :update, :destroy]
  # GET /workplaces
  # GET /workplaces.json
  def index
    @workplaces = Workplace.all
  end

  # GET /workplaces/1
  # GET /workplaces/1.json
  def show
  end

  # GET /workplaces/new
  def new
    @workplace = Workplace.new
  end

  # GET /workplaces/1/edit
  def edit
  end

  # POST /workplaces
  # POST /workplaces.json
  def create
    @workplace = Workplace.new(workplace_params)

    respond_to do |format|
      if @workplace.save
        format.html { redirect_to @workplace, notice: 'Workplace was successfully created.' }
        format.json { render :show, status: :created, location: @workplace }
      else
        format.html { render :new }
        format.json { render json: @workplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workplaces/1
  # PATCH/PUT /workplaces/1.json
  def update
    respond_to do |format|
      if @workplace.update(workplace_params)
        format.html { redirect_to @workplace, notice: 'Workplace was successfully updated.' }
        format.json { render :show, status: :ok, location: @workplace }
      else
        format.html { render :edit }
        format.json { render json: @workplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workplaces/1
  # DELETE /workplaces/1.json
  def destroy
    @workplace.destroy
    respond_to do |format|
      format.html { redirect_to workplaces_url, notice: 'Workplace was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workplace
      @workplace = Workplace.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workplace_params
      params.require(:workplace).permit(:name, :address, :request_limit, :created_by)
    end
end

app/helpers/workplaces_helper.rb
module WorkplacesHelper
end

app/views/workplaces/_form.html.erb
<%= simple_form_for(@workplace) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-group">
    <%= f.input :name, label: 'Name', input_html: { class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.input :address, label: 'Address', input_html: { class: "form-control"} %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

app/views/workplaces/edit.html.erb
<h1>Editing Workplace</h1>

<%= render 'form', workplace: @workplace %>

<%= link_to 'Show', @workplace %> |
<%= link_to 'Back', workplaces_path %>

app/views/workplaces/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Work Places</h3>

<%= link_to 'New Work Place', new_workplace_path, class: "btn btn-outline-info", type: "button" %>

<br> <br>

<table  id="basic-datatable" class="table dt-responsive nowrap w-100">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Created By</th>
            <th>Request Limit</th>
        </tr>
    </thead>
    <tbody>
      <% @workplaces.each do |w| %>
        <tr>
            <td><%= link_to w.name %></td>
            <td><%= w.address %></td>
            <td><%= User.first.id %></td>
            <td><%= w.request_limit %></td>
        </tr>
      <% end %>
    </tbody>
</table>

<br>

app/views/workplaces/new.html.erb
<h3>New Workplace</h3>

<%= render 'form', workplace: @workplace %>

<%= link_to 'Back', workplaces_path, class: "btn btn-light" %>

app/views/workplaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workplace.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @workplace.address %>
</p>

<p>
  <strong>Request limit:</strong>
  <%= @workplace.request_limit %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @workplace.created_by %>
</p>

<%= link_to 'Edit', edit_workplace_path(@workplace) %> |
<%= link_to 'Back', workplaces_path %>