config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :application_requests
  resources :workplaces
  get 'home/index'
  get 'users', to: "users#index"
	get 'users/new' => "users#new", as: :new_user
	post 'create_user' => "users#create_user", as: :create_user
  root 'workplaces#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_request.rb
class ApplicationRequest < ApplicationRecord
end

app/controllers/application_requests_controller.rb
class ApplicationRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_application_request, only: [:show, :edit, :update, :destroy]

  # GET /application_requests
  # GET /application_requests.json
  def index
    @application_requests = ApplicationRequest.all
  end

  # GET /application_requests/1
  # GET /application_requests/1.json
  def show
  end

  # GET /application_requests/new
  def new
    @application_request = ApplicationRequest.new
  end

  # GET /application_requests/1/edit
  def edit
  end

  # POST /application_requests
  # POST /application_requests.json
  def create
    @application_request = ApplicationRequest.new(application_request_params)

    respond_to do |format|
      if @application_request.save
        format.html { redirect_to @application_request, notice: 'Application request was successfully created.' }
        format.json { render :show, status: :created, location: @application_request }
      else
        format.html { render :new }
        format.json { render json: @application_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /application_requests/1
  # PATCH/PUT /application_requests/1.json
  def update
    respond_to do |format|
      if @application_request.update(application_request_params)
        format.html { redirect_to @application_request, notice: 'Application request was successfully updated.' }
        format.json { render :show, status: :ok, location: @application_request }
      else
        format.html { render :edit }
        format.json { render json: @application_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_requests/1
  # DELETE /application_requests/1.json
  def destroy
    @application_request.destroy
    respond_to do |format|
      format.html { redirect_to application_requests_url, notice: 'Application request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_request
      @application_request = ApplicationRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def application_request_params
      params.require(:application_request).permit(:work_place_id, :status, :verified_at, :rejected_at, :approved_at, :verified_by, :approved_by, :employee_list)
    end
end

app/helpers/application_requests_helper.rb
module ApplicationRequestsHelper
end

app/views/application_requests/_form.html.erb
<%= simple_form_for(@application_request) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-group">
    <%= f.label("Work Place", :work_place_id) %>
    <%= f.select :work_place_id, options_from_collection_for_select(Workplace.all, "id", "name"), { include_blank: true }, { class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label(:verified_at, :verified_at) %>
    <%= f.text_field :verified_at, class: "form-control",type: "date", autocomplete: :off  %>
  </div>

  <div class="form-group">
    <%= f.label(:rejected_at, :rejected_at) %>
    <%= f.text_field :rejected_at, class: "form-control",type: "date", autocomplete: :off  %>
  </div>

  <div class="form-group">
    <%= f.label(:approved_at, :approved_at) %>
    <%= f.text_field :approved_at, class: "form-control",type: "date", autocomplete: :off  %>
  </div>

  <div class="form-group">
    <%= f.label("Verified By", :verified_by) %>
    <%= f.select :verified_by, options_from_collection_for_select(User.all, "id", "email"), { include_blank: true }, { class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label("Approved By", :approved_by) %>
    <%= f.select :approved_by, options_from_collection_for_select(User.all, "id", "email"), { include_blank: true }, { class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label(:employee_list, :employee_list) %>
    <%= f.input :employee_list, label: false, class: "form-control-file" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

app/views/application_requests/edit.html.erb
<h1>Editing Application Request</h1>

<%= render 'form', application_request: @application_request %>

<%= link_to 'Show', @application_request %> |
<%= link_to 'Back', application_requests_path %>

app/views/application_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Application Requests</h3>

<%= link_to 'New Application Request', new_application_request_path, class: "btn btn-outline-info", type: "button" %>

<br> <br>

<table  id="basic-datatable" class="table dt-responsive nowrap w-100">
    <thead>
        <tr>
            <th>Work Place</th>
            <th>Status</th>
            <th>Verified At</th>
            <th>Rejected At</th>
            <th>Approved At</th>
            <th>Verified By</th>
            <th>Approved By</th>
        </tr>
    </thead>
    <tbody>
      <% @application_requests.each do |w| %>
        <tr>
            <td><%= link_to Workplace.find(w.work_place_id).name %></td>
            <td><%= "testing" %></td>
            <td><%= DateTime.now().strftime("%d-%m-%Y") %></td>
            <td><%= %></td>
            <td><%=  %></td>
            <td><%= User.first.id %></td>
            <td><%=  %></td>
        </tr>
      <% end %>
    </tbody>
</table>

<br>

app/views/application_requests/new.html.erb
<h1>New Application Request</h1>

<%= render 'form', application_request: @application_request %>

<%= link_to 'Back', application_requests_path, class: "btn btn-light" %>

app/views/application_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Work place:</strong>
  <%= @application_request.work_place_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @application_request.status %>
</p>

<p>
  <strong>Verified at:</strong>
  <%= @application_request.verified_at %>
</p>

<p>
  <strong>Rejected at:</strong>
  <%= @application_request.rejected_at %>
</p>

<p>
  <strong>Approved at:</strong>
  <%= @application_request.approved_at %>
</p>

<p>
  <strong>Verified by:</strong>
  <%= @application_request.verified_by %>
</p>

<p>
  <strong>Approved by:</strong>
  <%= @application_request.approved_by %>
</p>

<p>
  <strong>Employee list:</strong>
  <%= @application_request.employee_list %>
</p>

<%= link_to 'Edit', edit_application_request_path(@application_request) %> |
<%= link_to 'Back', application_requests_path %>